//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=Pristup odepren;
        ///Authorization=Nejsi autorizovan pro tento prikaz;
        ///ChannelIn=Tento kanal je jiz v db;
        ///UserSc=Uspesne pridan ;
        ///InvalidName=Neplatne jmeno;
        ///MessageQueueWasReloaded=Fronta zprav byla uspesne vyprazdnena!;
        ///Feed1=Kanal jiz ma seznam zmen spusten;
        ///Feed2=Seznam zmen je spusten;
        ///InvalidWiki=Neplatna wiki;
        ///Wiki+=Wiki pridana;
        ///Wiki-=Wiki smazana;
        ///Feed3=Kanal nema seznam zmen;
        ///Feed4=Chyba, ;
        ///Feed5=: Spatny pocet parametru;
        ///InvalidUser=Neplatny uzivatel;
        ///Language=Od ted t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cs_czech {
            get {
                return ResourceManager.GetString("cs_czech", resourceCulture);
            }
        }
        
        internal static string de_german {
            get {
                return ResourceManager.GetString("de_german", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=Permission denied;
        ///Authorization=You are not authorized to perform this, sorry;
        ///ChannelIn=This channel is already in db;
        ///UserSc=Successfuly added ;
        ///InvalidName=Invalid name;
        ///MessageQueueWasReloaded=Message queue was reloaded!;
        ///Feed1=Channel had already feed enabled;
        ///Feed2=Feed is enabled;
        ///InvalidWiki=Invalid wiki;
        ///Wiki+=Wiki inserted;
        ///Wiki-=Wiki removed;
        ///Feed3=Channel doesn&apos;t have enabled recent changes;
        ///Feed4=Error, ;
        ///Feed5=: Wrong number of parameters;
        ///InvalidUser=Invalid us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string zh_chinese {
            get {
                return ResourceManager.GetString("zh_chinese", resourceCulture);
            }
        }
    }
}
