//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=Pristup odepren;
        ///Authorization=Nejsi autorizovan pro tento prikaz;
        ///ChannelIn=Tento kanal je jiz v db;
        ///UserSc=Uspesne pridan ;
        ///InvalidName=Neplatne jmeno;
        ///MessageQueueWasReloaded=Fronta zprav byla uspesne vyprazdnena!;
        ///Feed1=Kanal jiz ma seznam zmen spusten;
        ///Feed2=Seznam zmen je spusten;
        ///InvalidWiki=Neplatna wiki;
        ///Wiki+=Wiki pridana;
        ///Wiki-=Wiki smazana;
        ///Feed3=Kanal nema seznam zmen;
        ///Feed4=Chyba, ;
        ///Feed5=: Spatny pocet parametru;
        ///InvalidUser=Neplatny uzivatel;
        ///Language=Od ted t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cs_czech {
            get {
                return ResourceManager.GetString("cs_czech", resourceCulture);
            }
        }
        
        internal static string pt_portugese {
            get {
                return ResourceManager.GetString("pt_portugese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=Zugriff verweigert;
        ///Authorization=Du bist nicht berechtigt diese durchzuführen, Tut mir leid;
        ///ChannelIn=Dieser Kanal ist bereits in der Datenbank;
        ///UserSc=Erfolgreich hinzugefügt ;
        ///InvalidName=Ungültiger Namen;
        ///MessageQueueWasReloaded=Nachricht Queue wurde neu geladen!;
        ///Feed1=Kanal hat bereits Feeds eingeschaltet;
        ///Feed2=Feed is ist aktiviert;
        ///InvalidWiki=Ungültiges wiki;
        ///Wiki+=Wiki hinzugefügt;
        ///Wiki-=Wiki entfernt;
        ///Feed3=Kanal hat letzten Änderungen nicht aktiviert;
        ///Feed4=Fehler, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string de_german {
            get {
                return ResourceManager.GetString("de_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=Permission denied;
        ///Authorization=You are not authorized to perform this, sorry;
        ///ChannelIn=This channel is already in db;
        ///UserSc=Successfuly added ;
        ///InvalidName=Invalid name;
        ///MessageQueueWasReloaded=Message queue was reloaded!;
        ///Feed1=Channel had already feed enabled;
        ///Feed2=Feed is enabled;
        ///InvalidWiki=Invalid wiki;
        ///Wiki+=Wiki inserted;
        ///Wiki-=Wiki removed;
        ///Feed3=Channel doesn&apos;t have enabled recent changes;
        ///Feed4=Error, ;
        ///Feed5=: Wrong number of parameters;
        ///InvalidUser=Invalid us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string es_spanish {
            get {
                return ResourceManager.GetString("es_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidName=존재하지 않는 이름입니다.;
        ///PermissionDenied=접근이 거부되었습니다.;
        ///Authorization=죄송합니다. 이 명령을 실행할 권한이 부족합니다.;
        ///ChannelIn=이 채널은 이미 데이터베이스에 있습니다.;
        ///UserSc=성공적으로 추가되었습니다.;
        ///MessageQueueWasReloaded=메시지 목록이 다시 로드되었습니다.;
        ///Feed1=이 채널에서 이미 피드가 활성화되었습니다.;
        ///Feed2=피드가 활성화되었습니다.;
        ///InvalidWiki=존재하지 않는 위키입니다.;
        ///Wiki+=위키가 추가되었습니다.;
        ///Wiki-=위키가 삭제되었습니다.;
        ///Feed3=채널에서 최근바뀜 수신을 활성화하지 않았습니다.;
        ///Feed4=에러, ;
        ///Feed5=잘못된 변수입니다;
        ///InvalidUser=존재하지 않는 사용자입니다;
        ///Language=이곳에선 한국어로 이야기하겠습니다;
        ///InvalidCode=죄송합니다. 그런 언어는 몰라요;
        ///LanguageInfo=이 명령어는  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ko_korean {
            get {
                return ResourceManager.GetString("ko_korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied=存取被拒;
        ///Authorization=抱歉，您无权执行此操作;
        ///ChannelIn=数据库中已有此频道;
        ///UserSc=已成功添加;
        ///InvalidName=名称无效;
        ///MessageQueueWasReloaded=已加载消息队列！;
        ///Feed1=已在此频道启用供稿;
        ///Feed2=供稿已启用;
        ///InvalidWiki=无效wiki;
        ///Wiki+=Wiki已插入;
        ///Wiki-=Wiki已移除;
        ///Feed3=频道没有启用最近更改;
        ///Feed4=错误，;
        ///Feed5=：参数个数错误;
        ///InvalidUser=无效用户;
        ///Language=我将在这里说中文;
        ///InvalidCode=抱歉，我不会这个语言;
        ///LanguageInfo=此命令将更改我在此频道使用的语言;
        ///Silence1=频道静音模式已经禁用;
        ///Silence2=现在起输出不再被停止。;
        ///SilenceBegin=我不会在这里说话，直到你停用这个;
        ///Feed6=频道已启用供稿;
        ///Feed7=已禁用供稿;
        ///Feed8=错误 $1 个参数。你需要提供两个参数;
        ///Config [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_chinese {
            get {
                return ResourceManager.GetString("zh_chinese", resourceCulture);
            }
        }
    }
}
